### PR TITLE
This tries to update the vignettes

### PR DESCRIPTION
**Pull request by MarcWeber**
I am new to Flutter so maybe there are better ways to do it.

Also some demos only seem to have animations on the apps not Web targets (?).

Pick what you need as you see fit.

Also I noticed that the vignettes eventually could be improved by providing better apis such as the tabs using indexed lists .. Shouldn't there be an option to pass the contents via children: or alike ? .. 

But its a repository to show off designs and that's what it does perfectly

### CODE REVIEW

**Comment by esDotDev** [comment]
Hi, thanks for the work! Could you go into a bit more detail about the changes here? Is it just conversion to NNBD, what else was done?

**Comment by MarcWeber** [comment]
The first commit just tries to make all work. The following two try to update to latest libraries and allow null safety. -------- Ursprüngliche Nachricht --------Von: Shawn ***@***.***>Datum: Fr., 25. Nov. 2022, 21:55An: gskinnerTeam/flutter_vignettes ***@***.***>Cc: Marc Weber ***@***.***>, Author ***@***.***>Betreff: Re: [gskinnerTeam/flutter_vignettes] This tries to update the vignettes (PR #22)
Hi, thanks for the work! Could you go into a bit more detail about the changes here? Is it just conversion to NNBD, what else was done?

**Comment by esDotDev** [comment]
Finally had some time to do a review on this. I think I can take it from here, but in general the issues are
* excessive use of `late` it looks like many defaults can be set initially, which avoids the need for `late` much of the time. ie, instead of `late int foo` can just do `int foo = 0`, or `late List foo;` do `List foo = [];`.
* similarly, many fields seems like they can probably be non-null w/ default, which leads to the next issue...
* overuse of `!` operator, mainly due to things being declared as nullable, rather than just get a default value

Super helpful work though! Shouldn't take too long to do a bit of cleanup and land it.

**Comment by MarcWeber** [comment]
My goal only was to have it run on latest Flutter to understand how it works. To take it from there I eventually some features/modules/ UI components even should be put into their own libraries. Cause you rarely use all. But still guessing. I totally agree that the work spent here might requires some more love in the future (cleanup).

I totally agree with your feedback.

**Comment by esDotDev** [comment]
Closing this as we have another branch where this is happening now, thanks again for the 1st effort!
https://github.com/gskinnerTeam/flutter_vignettes/pull/25

**Pull request closed without merging**
