### PR TITLE
Nnbd

### PR DESCRIPTION
**Pull request by esDotDev**
Migrate the codebase to the current version of Flutter and add support for NNBD.

We need to update the following modules:
  - [x] _shared
  - [x] basketball_ptr
  - [x] bubble_tab_bar
  - [x] constellations_list
  - [x] dark_ink_transition
  - [x] dog_slider
  - [x] drink_reward_list
  - [x] fluid_nav_bar
  - [x] gooey_edge
  - [x] indie_3d
  - [x] parallax_travel_cards_hero
  - [x] parallax_travel_cards_list
  - [x] particle_swipe
  - [x] plant_forms
  - [x] product_detail_zoom
  - [x] sparkle_party
  - [x] spending_tracker
  - [x] ticket_fold

### CODE REVIEW

**Comment by esDotDev** [comment]
@SoroushBeigi I was thinking you could start with any of:
- basketball_ptr, 
- bubble_tab_bar, 
- fluid_nav_bar 
- gooey_edge

Does that sound ok? I'll get going on the rest in the meantime.

**Comment by SoroushBeigi** [comment]
@esDotDev Sure, I will start as soon as possible

**Comment by esDotDev** [comment]
@SoroushBeigi Sounds good! I've already gotten quite a few done today.

fyi, the easiest way I've found to fix the android build files, is:
1. Delete /android
2. Run ` flutter create --platforms android  --org com.gskinner.package_id .`
3. Delete /test folder

**Comment by SoroushBeigi** [comment]
Good to hear! we're gonna finish them soon. 
Thanks for the advice, my last try was creating a new flutter project and moving the dart files, this is obviously a better choice.

**Comment by SoroushBeigi** [comment]
@esDotDev We are almost done here, should I update "plant_forms" too or you will do it?

**Comment by esDotDev** [comment]
I'm in the middle of doing plant_forms, it's a pretty big one, and I also want to refactor it a bit as I'm not super happy with the implementation. Should be done monday!

**Comment by SoroushBeigi** [comment]
Alright, thanks for keeping me updated. please let me know if there were anything I could help with.

**Comment by SoroushBeigi** [comment]
@esDotDev I'm assuming the nnbd fix is done with your last commit, so I wanted to know why aren't we merging this branch?

**Comment by esDotDev** [comment]
No, there's a bug with the current form implementation, so it's still a WIP. Got pulled away last week on some other project, but will try and get this closed out today.

**Comment by SoroushBeigi** [comment]
Okay. good luck with that, and tell me if I could help with anything

**Comment by esDotDev** [comment]
@SoroushBeigi I'm done (for now) with plant_forms :) I ended up abandoning the refactor for now, and just did the minimum required for `nnbd`, I can follow up with a seperate PR for the refactor. 

Would you mind giving me a bit of a sanity check and just make sure you can open each of the demos and run them? Everything is looking good on my end.

**Comment by SoroushBeigi** [comment]
@esDotDev Alright, hope everything goes well with that :) 
Sure, I will try to check them all today. Will let you know asap

**Comment by SoroushBeigi** [comment]
@esDotDev I checked them all and everything works fine, there were only small overflow problems in 2 demos which I fixed in recent  commits. will attach before and after screenshots, of course you may think of better ways to fix the overflow. they happened on Pixel XL emulator (5.5"). I also updated maximum dart sdk to 3.3.1 because it is recently released.
parisBefore
parisAfter
dogBefore
dogAfter

**Pull request merged**
